#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1='[\u@\h \W]\$ '

# Get dotfiles directory
if [ -d "$HOME/.dotfiles" ]; then
    DOTFILES_DIR="$HOME/.dotfiles"
else
    echo "Unable to find dotfiles, exiting."
    return
fi

# Source bash config files
for DOTFILE in "$DOTFILES_DIR"/bash/{aliases,custom}; do
    [ -f "$DOTFILE" ] && . "$DOTFILE"
done

# Change date/time format of ls command
export TIME_STYLE=long-iso

# Add editor for yaourt
export VISUAL="nvim"

# Clean up
unset DOTFILE

# Export
export DOTFILES_DIR
